name: Build project and run Lighthouse CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          uploadArtifacts: true
          temporaryPublicStorage: false
          configPath: "./.lighthouserc.json"
